import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Pokeropa</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://listado.mercadolibre.com.ar/ropa-pokemon">Pokeropa!</a>
//         </h1>

//         <p className={styles.description}>
//           ¡Welcome!
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card1}>
//             <h2>Ropa Masculina &rarr;</h2>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card2}>
//             <h2>Ropa Femenina &rarr;</h2>
//           </a>

//           <a
//             href="https://listado.mercadolibre.com.ar/pokemon-ropa-bebes"
//             className={styles.card3}
//           >
//             <h2>Ropa Niños &rarr;</h2>
//           </a>

         
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://es-la.facebook.com/julianagustin.murno/"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' Julian '}
//           <span className={styles.logo}>
//             <Image src="/favicon.ico" alt="Vercel Logo" width={16} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }


import { Navbar, Button, Link, Text } from "@nextui-org/react";

import { AcmeLogo } from "../components/AcmeLogo.js";
import Layout from '../Layout/Layout';

export default function Home() {
  return (
 <Layout>

  <h1>Hola mundo</h1>
 </Layout>
    
  )
}